# memberships/urls.py
from django.urls import path

from memberships.views import MembershipSelectView,PaymentView,UpdateTransactionRecords,CancelSubscription

app_name = 'memberships'

urlpatterns = [
    path('memberships/', MembershipSelectView.as_view(), name='select_membership'),
    path('payments/', PaymentView, name='payment'),
    path('update_transaction/<subscription_id>/update/', UpdateTransactionRecords, name='update_transaction'),
    path('cancel/', CancelSubscription, name='cancel')

]

Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    # path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, create_category, create_course, create_lesson

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('Create/Category', create_category, name='create_category'),
    path('Create/Course', create_course, name='create_course'),
    path('Create/Lesson', create_lesson, name='create_lesson')
]

courses/models.py
from django.db import models
# from memberships.models import Membership
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    Title = models.CharField(max_length=150)
    Description = models.TextField(max_length= 200, null=True)
    Image = models.ImageField(upload_to='Category_Images', default='Category_Images/default.jpg')

    def __str__(self):
        return '{}'.format(self.Title)

class Course(models.Model):
    Creator = models.ForeignKey(User,on_delete = models.CASCADE)
    slug = models.SlugField()
    Title = models.CharField(max_length=90)
    Category = models.ForeignKey(Category,on_delete=models.CASCADE)
    Description = models.TextField(max_length=400)
    Time_Created = models.DateTimeField(auto_now=True)
    Image = models.ImageField(upload_to='Course_Images', default='Course_Images/default.jpg')
    Level = models.IntegerField()

    def __str__(self):
        return self.Title

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    # def get_courses_related_to_memberships(self):
    #     return self.courses.all()

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('Position')




class Lesson(models.Model):
    slug = models.SlugField()
    Title = models.CharField(max_length=64,default='')
    Course = models.ForeignKey(Course,on_delete=models.CASCADE)
    Video_id = models.FileField(upload_to='video_lessons',default='')
    Position = models.IntegerField()

    def __str__(self):
        return self.Title

    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.Course.slug,'lesson_slug':self.slug})

courses/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Category, Course, Lesson



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['Title', 'Description', 'Image']
        help_texts = {
            'Title': 'Mysal üçin Geometriýa, Matematika we ş.m.',
            'Description':'Kategoriýanyň gysgaça düşündirilişini giriziň',
            'Image':'Kategoriýanyň suratyny goýup bilersiňiz'
        }
        labels = {
            'Title':'Ady',
            'Description':'Düşündiriş',
            'Image':'Surat',
        }

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['Creator','slug', 'Title', 'Category', 'Description', 'Image', 'Level', ]
        help_texts = {
            'Title': 'Kursuňyzyň adyny giriziň',
            'Description':'Kursuň gysgaça beýanyny goýuň',
            'Category':'Kurs döredjek kategoriýany saýlaň',
            'Level':'Kursuňyza bir dereje girizin',
            'Image':'Kursuň suratyny goýup bilersiňiz ýa-da boş goýup bilersiňiz',
        }
        labels = {
            'Title':'Ady',
            'Description':'Düşündiriş',
            'Category':'Kategoriýa',
            'Level':'Dereje',
            'Image':'Surat',

        }
        widgets = {'Creator': forms.HiddenInput(), 'slug': forms.HiddenInput()}


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['slug','Title', 'Course', 'Video_id', 'Position', ]
        help_texts = {
            'Title':'Sapagyň adyny giriziň',
            'Kurs':'Bu sapagyň kursuny saýlaň',
            'Video_id':'Video sapagyny saýlaň',
            'Position':'Sapak tertibini giriziň'
        }
        labels = {
            'Title':'Ady',
            'Course':'Kurs',
            'Position':'Tertibi',
        }
        widgets = {
            'slug': forms.HiddenInput()
        }

courses/views.py
import secrets
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,DetailView,View
from courses.models import Course,Lesson,Category
# from memberships.models import UserMembership
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CategoryForm, CourseForm, LessonForm
# Create your views here.

class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['category'] = category
        return context

class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'



def CourseListView(request, category):
    courses = Course.objects.filter(Category=category)
    context = {
        'courses':courses
    }
    return render(request, 'courses/course_list.html', context)



class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = Course


class LessonDetailView(View,LoginRequiredMixin):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        context = {'lesson': lesson}
        return render(request, "courses/lesson_detail.html", context)


# @login_required
def SearchView(request):
    if request.method == 'POST':
        Search = request.POST.get('search')
        results = Lesson.objects.filter(Title__contains=Search)
        context = {
            'results':results
        }
        return render(request, 'courses/search_result.html', context)


@login_required
def create_category(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Kategoriýa döretmek isleseňiz ilki mugallym bolmaly !!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = CategoryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Kategoriýa üstünlikli döredildi !!')
            return redirect('courses:home')
    else:
        form = CategoryForm()
    context = {
        'form':form
    }
    return render(request, 'courses/create_category.html', context)


@login_required
def create_course(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Kurs döretmek isleseňiz ilki mugallym bolmaly !!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            Category = form.cleaned_data['Category']
            slug = Category.id
            messages.success(request, f'Kurs üstünlikli döredildi !!')
            return redirect('/courses/' + str(slug))
    else:
        form = CourseForm(initial={'Creator':request.user.id, 'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/create_course.html', context)


@login_required
def create_lesson(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Sapak döretmek isleseňiz ilki mugallym bolmaly !!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = LessonForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            Course = form.cleaned_data['Course']
            slug = Course.slug
            messages.success(request, f'Sapak üstünlikli döredildi !!')
            return redirect('/Create/Lesson')
    else:
        form = LessonForm(initial={'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/create_lesson.html', context)


def view_404(request, exception):
    return render(request, '404.html')

def view_403(request, exception):
    return render(request, '403.html')

def view_500(request):
    return render(request, '500.html')

# def get(self,request,course_slug,lesson_slug,*args,**kwargs):
#
#     course_qs = Course.objects.filter(slug=course_slug)
#     if course_qs.exists():
#         course = course_qs.first()
#     lesson_qs = course.lessons.filter(slug=lesson_slug)
#     if lesson_qs.exists():
#         lesson = lesson_qs.first()
#     user_membership = UserMembership.objects.filter(user=request.user).first()
#     user_membership_type = user_membership.membership.membership_type
#
#     course_allowed_membership_type = course.allowed_memberships.all()
#     context = {'lessons':None}
#
#     if course_allowed_membership_type.filter(membership_type=user_membership_type).exists():
#         context = {'lesson':lesson}
#
#     return render(request,'courses/lesson_detail.html',context)

courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Ukyply</a>
      <a href="/#Courses">Kategoriýalar</a>
      <span>Kurs</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Gözle</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
            <input name="search" type="text" placeholder="Kurs Gözle">
            <button type="submit" class="site-btn btn-dark">Kurs Gözle</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->


<!-- single course section -->
<section class="single-course spad pb-0">
  <div class="container">
    <div class="course-meta-area">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">

          <h3>{{course.Title|capfirst}}</h3>
          <div class="course-metas">
            <div class="course-meta">
              <div class="course-author">
                <h6>Kursun Mugallymy</h6>
                <p>{{course.Creator|capfirst}}, <span> Mugallym</span></p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Kategoriya</h6>
                <p>{{ course.Category }}</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Düşündiriliş</h6>
                <p>{{course.Description}}</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Sapaklaryn Sany</h6>
                <p>{{ course.lessons|length }}</p>
              </div>
            </div>
          </div>
          <a href="javascript:history.back()" class="site-btn price-btn">Yza</a>
          <a href="#Go" class="site-btn buy-btn">Öwrenmage Dowam Edin</a>
        </div>
      </div>
    </div>
    <img src="img/courses/single.jpg" alt="" class="course-preview">
    <div class="row">
      <div class="col-lg-10 offset-lg-1 course-list">
        <div class="cl-item" id="lessons">
          <h4>Kursun Sapaklary</h4>
          {% if course.lessons != None  %}
            {% for lesson in course.lessons %}
            <div data-aos="fade-right" >
              <h5 class="pb-3">Sapak {{lesson.Position}} <a id="Go" href="{{ lesson.get_absolute_url }}#video"><span class="pl-4">{{lesson.Title}}</span></a></h5>
            </div>
            {% endfor %}
          {% endif %}
          {% if course.lessons|length == 0 %}
          <div class="alert alert-danger">Bu Kursda Entak Sapak Yok !</div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/1.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Ukyply</a>
      <span>Kategoriýalar</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Kurs Gözle</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
            <input name="search" type="text" placeholder="Kurs Gözle">
            <button type="submit" class="site-btn btn-dark">Kurs Gözle</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->

<div class="course-warp">
  <ul class="course-filter controls">
    <li class="control active" data-filter="all">Bu kategoriýanyň ähli kurslary</li>
  </ul>
<div class="featured-courses">

      <div class="featured-course course-item">
        <div class="row">
          {% for course in courses %}
          <div class="col-lg-6 pb-4">
            <div class="course-info">
              <div class="course-text">
                <h5>{{course.Class}}</h5>
                <a href="{% url 'courses:course_detail' course.slug %}"><h3 class="">{{ course.Title|capfirst }}</h3></a>
                <p>{{course.Description}}</p>
                <div class="students"><a href="{% url 'courses:course_detail' course.slug %}" class="btn btn-primary">Kurs Sapaklary</a></div>
              </div>
              <div class="course-author">
                <div class="ca-pic set-bg" data-setbg="{{ request.user.profile.profile_pic.url }}"></div>
                <p><span>{{course.Creator|capfirst}}</span> Mugallym Tarapyndan Yasaldy . </p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

courses/templates/courses/create_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Kategoriýa Döret</h1>
        <form method="post" action="/Create/Category" enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Kategoriýa Döret</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/create_course.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Kurs Döret</h1>
        <form method="post" action="/Create/Course" enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Kurs Döret</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/create_lesson.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Sapak Döret</h1>
        <form method="post" action="/Create/Lesson" enctype="multipart/form-data">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Sapak Döret</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'base.html' %}
{% load static %}
{% block post_detail_link %}

{% endblock %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Ukyply</a>
      <a href="/#Courses">Kategoriýalar</a>
      <a href="#">Kurs</a>
      <span>Sapak {{ lesson.Position }}</span>
    </div>
  </div>
</div>
  <!-- {% if lesson is not None %}
	<li class="form-control"><a  href="{{ lesson.course.get_absolute_url }}">Mesimi : {{ lesson.course.titulli }}</a></li>
	<li class="form-control">Title : {{ lesson.titulli }}</li>
  {% endif %} -->

<!-- Page info end -->

	<div  id="video" class='container'>
		<div class="alert alert-info" role="alert">
			Doly Ekrana Geçmek Üçin Video 2 Gezek Basyn
		  </div>
		<h1>{{ lesson.Title }}</h1>
		<div class='row'>
			<div class='col-sm-12 col-md-12'>
				{% if lesson is not None %}

				<!-- <iframe id="video" width="100%" height="450px" src="{{ lesson.video_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
        <video id="video" width="100%" height="630px" controls autoplay >
          <source src="{{ lesson.Video_id.url }}" type="video/mp4"/>
        </video>
				<div class="text-center">
				<a href="javascript:history.back()" class="mb-5 mt-2 btn btn-primary">Yza</a>
				</div>

				{% else %}
				<!-- <h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select_membership' %}"><button class="btn btn-warning">Upgrade Membership</button></a>
				<hr> -->
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}

courses/templates/courses/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-top-bg.jpg'%}">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <br><br>
        <br>
        <br><br>
        <br>
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Gözle">
          <button type="submit" class="site-btn">Gözle</button>
        </form>
      </div>
    </div>
  </div>
</section>
<div class="container">
    <h1 class=" mt-2 text-center">{{ results|length }} Netije Tapyldy :</h1>
    <div class="row course-items-area">
        <!-- course -->
        {% if results %}
        {% for lesson in results %}
        <div class="mix col-lg-4 col-md-4 col-sm-6 finance">
          <div class="course-item">
              <a href="/courses/{{ lesson.slug }}/">
            <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            </div>
            <div class="course-info">
              <div class="course-text">
                <h5>{{ lesson.Title }}</h5>
                <p>{{ lesson.Course }}</p>
                <div class="students">{{ course.Category }}</div>
              </div>
            </a>
            </div>
          </div>
        </div>
        {% endfor %}

        {% else %}
        <div class="text-center">
            <h4>Netije Tapylmady .</h4>
        </div>
        {% endif %}
        <!-- course -->
      </div>
</div>



{% endblock %}