Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    # path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, create_category, create_course, create_lesson

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('Create/Category', create_category, name='create_category'),
    path('Create/Course', create_course, name='create_course'),
    path('Create/Lesson', create_lesson, name='create_lesson')
]

users/urls.py
from django.urls import path

from users.views import Profile,Request

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('Request/', Request, name='Request')

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/About.jpg' %}" style="height:100% ;background-attachment: fixed;">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Ukyply</a>
      <span>Kurslar</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-primary'>Mirsevini!</h1>
		    <h2>Mesoni me shume rreth nesh</h2>
		    <hr>
		    <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etae magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		    <button type="button" class="btn btn-primary">Let's Know More</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Ukyply - Online Learning Platform</title>
	<meta charset="UTF-8">
	<meta name="description" content="Ukyply Online Learning System">
	<meta name="keywords" content="Class , Learning , Ukyply , Online Learning">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/Ukyply_Logo.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav" style="padding:10px">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/Ukyply_Full_Logo.png' %}" alt="" style="height:55px "></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}">Baş Sahypa</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#Courses">Kurslar</a>
				  </li>
			  </li>
<!-- 			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:create_category' %}">Kategoriýa Goş</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:create_course' %}">Kurs Goş</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:create_lesson' %}">Sapak Goş</a>
			  </li>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Habarlaşyň</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">Biz Barada</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:post_list' %}">Blog</a>
			  </li>
			  {% endif %}
			  {% if request.user.is_authenticated %}

			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>

				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Profil</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Hasapdan <br> Çykmak</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Giriş</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Hasap Aç</a>
			  </li>
              {% endif %} -->
			    <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Habarlaşyň</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">Biz Barada</a>
			  </li>
			</ul>
		  </div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

<!-- {% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Ulgamymyza goşulyň!</h2>
				<p>Videolar, mugallymlar we beýleki agzalar bilen aragatnaşyk arkaly onlaýn sapaklary öwreniň. Bu gaty ýönekeý, etmeli ýeke-täk zadyňyz hasaba alynmak. Aşakdaky düwmä basyň:</p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Agza Bol</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %} -->


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row text-center">
					<div class="widget-item">

					</div>
					<div class="widget-item">
						<h4>Gözleg</h4>
						<ul>
							<li><a href="/blog">Blog</a></li>
							<li><a href="/about">Biz Barada</a></li>
							<li><a href="/contact">Habarlaşyň</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4 style="margin-bottom:0px">Aragatnaşykda Boluň</h4>
						<ul class="contact-list">
							<li>Türkmenistan <br>Aşgabat</li>
							<li>+993 63 000000</li>
							<li>support@ukyply.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Kategoriyalar</h4>
						<ul>
							<li><a href="/courses/1">Matematika</a></li>
							<li><a href="/courses/2">Biologiýa</a></li>
							<li><a href="/courses/3">Fizika</a></li>
							<li><a href="/courses/4">Himiýa</a></li>
							<li><a href="/courses/5">Informatika</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<div class="">
	Awtorlyk hukugy &copy; Ukyply <script>document.write(new Date().getFullYear());</script> Ähli hukuklar goralandyr
</div>
<small>IT Meydança Bilen Bilelikde Işlenilendir</small>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}" style="background-attachment:fixed">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Ukyply</a>
      <span>Aragatnaşykda Bol</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<!-- <section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Kurs</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1"> -->
          <!-- search form -->
          <!-- <form class="course-search-form">
            <input type="text" placeholder="Kurs">
            <input type="text" class="last-m" placeholder="Kategoriýa">
            <button class="site-btn btn-dark">Kurs Gözle</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section> -->
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Aragatnaşykda boluň</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. </p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Adyňyz">
            <input type="text" placeholder="Siziň emailiňiz">
            <input type="text" placeholder="Tema">
            <textarea placeholder="Hat"></textarea>
            <button class="site-btn">Hat iberiň</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Habarlaşmak üçin maglumat</h2>
            <p>Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendi sse cursus faucibus finibus.</p>
          </div>
          <div class="phone-number">
            <span>Habarlaşmak üçin</span>
            <h2>+993 64 000000</h2>
          </div>
          <ul class="contact-list">
            <li>Aşgabat ş. <br>Kemine köçesi 14-nji jaý</li>
            <li>+993 64 000001</li>
            <li>support@ukyply.com</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}" style="background-attachment:fixed">
  <div class="container">
    <div class="hero-text text-white" style="padding:200px 0 0">
      {% if request.user.is_authenticated %}
      <h2>Gaýtadan hoş geldiňiz {% if request.user.profile.is_teacher == True %}
         Mugallym ,
        {% endif %} {{ request.user.username|capfirst }}


      </h2>
      {% else %}
      <h2>Onlaýn öwreniň - Okamagyň täze döwri</h2>
      {% endif %}
      <p>Ukyply , size gymmatlyk goşjak käbir zatlary öwrenmäge kömek edýän onlaýn okuw ulgamydyr.</p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Kurs Gözle">
          <button type="submit" class="site-btn">Kurs Gözle</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="Courses">Kategoriýalar</h2>
      <p>Kategoriýaňyzy saýlaň .</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">

          <div class="ci-thumb set-bg" data-setbg="{{ cat.Image.url }}"></div>
          <div class="ci-text" style="height:50px ; padding:15px">
            <a href="/courses/{{ cat.id }}">

            <h5>{{ cat.Title|capfirst }}</h5>
            <!-- <p>{{ cat.Description|capfirst }}</p> -->
            <!-- <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Look At The Subjects</a></span> -->
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->


{% endblock content %}